version: "3.8"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/local.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      - ml
    networks:
      - dev_net

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    environment:
      ML_BASE_URL: http://ml:9000
      DB_HOST: mysql
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backendWorkspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ml
      - mysql
    networks:
      - dev_net

  ml:
    build:
      context: ./ml
    container_name: ml
    ports:
      - "9000:9000"
    volumes:
      - ./ml:/mlWorkspace
    networks:
      - dev_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_net

volumes:
  mysql_data:

networks:
  dev_net:
    driver: bridge